export const curriculum = [
  {
    id: 'module-1',
    title: 'Cybersecurity Fundamentals',
    icon: '🛡️',
    level: 'Beginner',
    lessons: [
      {
        id: 'lesson-1-1',
        title: 'What is Cybersecurity?',
        description: 'Introduction to cybersecurity, why it matters, and the threat landscape.',
        topics: ['Definition of cybersecurity', 'Why cybersecurity matters', 'Types of cyber threats', 'Real-world impact of breaches'],
      },
      {
        id: 'lesson-1-2',
        title: 'The CIA Triad',
        description: 'Confidentiality, Integrity, and Availability — the three pillars of information security.',
        topics: ['Confidentiality', 'Integrity', 'Availability', 'Real-world examples of each'],
      },
      {
        id: 'lesson-1-3',
        title: 'Types of Attackers & Motives',
        description: 'Understanding who the adversaries are and what drives them.',
        topics: ['Script kiddies', 'Hacktivists', 'Cybercriminals', 'Nation-state actors', 'Insider threats'],
      },
      {
        id: 'lesson-1-4',
        title: 'Security Mindset & Defense in Depth',
        description: 'How to think like a security professional and build layered defenses.',
        topics: ['Attacker vs defender mindset', 'Defense in depth', 'Principle of least privilege', 'Security policies'],
      },
    ],
  },
  {
    id: 'module-2',
    title: 'Linux for Security',
    icon: '🐧',
    level: 'Beginner',
    lessons: [
      {
        id: 'lesson-2-1',
        title: 'Linux Basics',
        description: 'Essential Linux commands every security professional must know.',
        topics: ['File system navigation', 'Creating/editing files', 'User management', 'Process management'],
      },
      {
        id: 'lesson-2-2',
        title: 'File Permissions & Ownership',
        description: 'Understanding and securing Linux file permissions.',
        topics: ['chmod, chown, chgrp', 'SUID, SGID, Sticky bit', 'Access control lists', 'umask'],
      },
      {
        id: 'lesson-2-3',
        title: 'Networking Commands',
        description: 'Linux commands for network reconnaissance and monitoring.',
        topics: ['ifconfig/ip', 'netstat/ss', 'nmap basics', 'tcpdump', 'curl & wget'],
      },
      {
        id: 'lesson-2-4',
        title: 'Bash Scripting for Security',
        description: 'Automate security tasks with Bash scripting.',
        topics: ['Variables & loops', 'Conditionals', 'Functions', 'Writing recon scripts'],
      },
    ],
  },
  {
    id: 'module-3',
    title: 'Networking Fundamentals',
    icon: '🌐',
    level: 'Beginner',
    lessons: [
      {
        id: 'lesson-3-1',
        title: 'OSI Model',
        description: 'The 7-layer model that defines how data travels across networks.',
        topics: ['All 7 layers explained', 'What happens at each layer', 'Common attacks per layer'],
      },
      {
        id: 'lesson-3-2',
        title: 'TCP/IP & Protocols',
        description: 'The protocols that power the internet and how attackers exploit them.',
        topics: ['TCP vs UDP', 'IP addressing & subnetting', 'Common protocols (HTTP, DNS, DHCP, ARP)'],
      },
      {
        id: 'lesson-3-3',
        title: 'Firewalls & IDS/IPS',
        description: 'Network security controls that block and detect threats.',
        topics: ['Packet filtering', 'Stateful inspection', 'IDS vs IPS', 'Common firewall rules'],
      },
      {
        id: 'lesson-3-4',
        title: 'Network Scanning & Enumeration',
        description: 'How attackers discover targets and how defenders detect them.',
        topics: ['Port scanning concepts', 'Service enumeration', 'Banner grabbing', 'Passive vs active recon'],
      },
    ],
  },
  {
    id: 'module-4',
    title: 'Web Security',
    icon: '🕸️',
    level: 'Intermediate',
    lessons: [
      {
        id: 'lesson-4-1',
        title: 'HTTP/HTTPS Deep Dive',
        description: 'How the web works and where security vulnerabilities live.',
        topics: ['HTTP methods & status codes', 'Headers & cookies', 'HTTPS & TLS', 'Same-origin policy'],
      },
      {
        id: 'lesson-4-2',
        title: 'OWASP Top 10',
        description: 'The most critical web application security risks.',
        topics: ['Injection flaws', 'Broken authentication', 'Sensitive data exposure', 'Security misconfigurations'],
      },
      {
        id: 'lesson-4-3',
        title: 'SQL Injection',
        description: 'One of the most common and dangerous web vulnerabilities.',
        topics: ['How SQLi works', 'Types of SQL injection', 'Union-based & blind SQLi', 'Prevention techniques'],
      },
      {
        id: 'lesson-4-4',
        title: 'XSS, CSRF & Other Attacks',
        description: 'Client-side attacks that target web users.',
        topics: ['Reflected, Stored & DOM XSS', 'CSRF attacks', 'Clickjacking', 'Content Security Policy'],
      },
    ],
  },
  {
    id: 'module-5',
    title: 'Ethical Hacking',
    icon: '💻',
    level: 'Intermediate',
    lessons: [
      {
        id: 'lesson-5-1',
        title: 'Penetration Testing Basics',
        description: 'The methodology, ethics, and legal framework of pen testing.',
        topics: ['Pen testing phases', 'Rules of engagement', 'Legal considerations', 'Bug bounty programs'],
      },
      {
        id: 'lesson-5-2',
        title: 'Reconnaissance Techniques',
        description: 'Gathering intelligence on targets before an attack.',
        topics: ['OSINT techniques', 'Google dorking', 'Whois & DNS enumeration', 'Social engineering recon'],
      },
      {
        id: 'lesson-5-3',
        title: 'Exploitation Fundamentals',
        description: 'Understanding how vulnerabilities are exploited.',
        topics: ['Buffer overflows concept', 'Metasploit basics', 'Common exploit types', 'CVEs and public exploits'],
      },
      {
        id: 'lesson-5-4',
        title: 'Post-Exploitation & Reporting',
        description: 'What happens after initial access and how to document findings.',
        topics: ['Privilege escalation', 'Lateral movement concepts', 'Data exfiltration', 'Writing pentest reports'],
      },
    ],
  },
  {
    id: 'module-6',
    title: 'Cryptography',
    icon: '🔐',
    level: 'Intermediate',
    lessons: [
      {
        id: 'lesson-6-1',
        title: 'Encryption Fundamentals',
        description: 'How encryption protects data at rest and in transit.',
        topics: ['What is encryption?', 'Symmetric encryption', 'Key exchange problem', 'Common use cases'],
      },
      {
        id: 'lesson-6-2',
        title: 'Asymmetric Cryptography',
        description: 'Public key infrastructure and how it secures the internet.',
        topics: ['RSA algorithm', 'Elliptic curve cryptography', 'Digital signatures', 'Key management'],
      },
      {
        id: 'lesson-6-3',
        title: 'Hashing & Integrity',
        description: 'One-way functions and how they ensure data integrity.',
        topics: ['MD5, SHA family', 'Password hashing (bcrypt, Argon2)', 'Hash collisions', 'HMAC'],
      },
      {
        id: 'lesson-6-4',
        title: 'PKI & TLS/SSL',
        description: 'Certificate authorities and how HTTPS works under the hood.',
        topics: ['X.509 certificates', 'Certificate chains', 'TLS handshake', 'Common SSL/TLS attacks'],
      },
    ],
  },
  {
    id: 'module-7',
    title: 'Incident Response',
    icon: '🚨',
    level: 'Advanced',
    lessons: [
      {
        id: 'lesson-7-1',
        title: 'IR Lifecycle',
        description: 'The phases of responding to a security incident.',
        topics: ['Preparation', 'Detection & Analysis', 'Containment', 'Eradication & Recovery', 'Post-incident'],
      },
      {
        id: 'lesson-7-2',
        title: 'Digital Forensics Basics',
        description: 'Collecting and preserving evidence from compromised systems.',
        topics: ['Chain of custody', 'Disk imaging', 'Memory forensics', 'Log analysis', 'Timeline reconstruction'],
      },
      {
        id: 'lesson-7-3',
        title: 'Malware Analysis',
        description: 'Understanding how malware works and how to analyze it.',
        topics: ['Types of malware', 'Static analysis', 'Dynamic analysis', 'Sandbox environments'],
      },
      {
        id: 'lesson-7-4',
        title: 'Threat Intelligence',
        description: 'Using intelligence to stay ahead of attackers.',
        topics: ['IOCs & TTPs', 'MITRE ATT&CK framework', 'Threat feeds', 'Threat hunting basics'],
      },
    ],
  },
  {
    id: 'module-8',
    title: 'Advanced Topics',
    icon: '⚡',
    level: 'Advanced',
    lessons: [
      {
        id: 'lesson-8-1',
        title: 'CTF Strategy & Practice',
        description: 'How to approach Capture the Flag competitions.',
        topics: ['CTF categories', 'Web challenges', 'Reverse engineering', 'Crypto challenges', 'Forensics'],
      },
      {
        id: 'lesson-8-2',
        title: 'Cloud Security',
        description: 'Security challenges and best practices in cloud environments.',
        topics: ['AWS/Azure/GCP security', 'IAM misconfigurations', 'Container security', 'Serverless security'],
      },
      {
        id: 'lesson-8-3',
        title: 'Social Engineering',
        description: 'The human element of cybersecurity — the biggest vulnerability.',
        topics: ['Phishing techniques', 'Pretexting & vishing', 'Physical security', 'Security awareness training'],
      },
      {
        id: 'lesson-8-4',
        title: 'Certifications & Career Paths',
        description: 'Your roadmap to a cybersecurity career.',
        topics: ['CompTIA Security+, CEH, OSCP', 'Blue team vs red team', 'Building a home lab', 'Portfolio advice'],
      },
    ],
  },
  {
    id: 'module-9',
    title: 'Python for Cybersecurity',
    icon: '🐍',
    level: 'Intermediate',
    track: 'coding',
    description: 'Write safe, useful Python automation for security analysis and authorized labs.',
    lessons: [
      {
        id: 'lesson-9-1',
        title: 'Python for Security Automation',
        description: 'Build small, readable scripts that automate repetitive defensive security tasks.',
        topics: ['Python data types', 'Functions and modules', 'Reading files safely', 'Automation design'],
        learningObjectives: ['Choose the right Python data structure for a security task', 'Write a small reusable analysis function', 'Explain how automation can fail safely'],
        codeExample: 'from pathlib import Path\n\nfor path in Path("logs").glob("*.log"):\n    print(path.name)',
        exercise: {
          prompt: 'Write a function that counts non-empty lines in a provided text file. Keep the file path as an argument.',
          starterCode: 'def count_lines(file_path):\n    # return the number of non-empty lines\n    pass',
          expectedOutcome: 'A reusable function that reads the file and returns a count without changing the file.',
        },
        challenge: 'Create a safe directory inventory script for a provided lab folder. Report file names, extensions, and sizes without executing files.',
        hints: ['Start with pathlib.Path.', 'Use read_text only for files you explicitly need to inspect.', 'Test with a tiny fixture before scanning the whole lab folder.'],
        quizPrompt: 'Ask the learner why a security automation script should validate paths and avoid executing discovered files.',
        xpReward: 150,
      },
      {
        id: 'lesson-9-2',
        title: 'Log Analysis with Python',
        description: 'Turn authentication logs into useful signals without losing the original evidence.',
        topics: ['Parsing structured text', 'Regular expressions', 'Aggregation', 'Suspicious login patterns'],
        learningObjectives: ['Extract fields from a log line', 'Group events by user or source address', 'Describe the limits of simple heuristics'],
        codeExample: 'import re\n\npattern = re.compile(r"failed login user=(?P<user>\\w+) ip=(?P<ip>[^ ]+)")\nmatch = pattern.search(line)',
        exercise: {
          prompt: 'Parse the supplied failed-login lines and return a count of attempts per IP address.',
          starterCode: 'def failed_attempts_by_ip(lines):\n    counts = {}\n    # parse each line and update counts\n    return counts',
          expectedOutcome: 'A dictionary of IP addresses and failed-attempt counts, with malformed lines ignored safely.',
        },
        challenge: 'Investigate a simulated login log and identify the most likely password-spraying source, then explain the evidence and one false-positive risk.',
        hints: ['Count distinct usernames as well as total attempts.', 'Compare time windows instead of relying on a single event.', 'Do not label an IP malicious from one failed login.'],
        quizPrompt: 'Ask the learner to distinguish an indicator from proof when analyzing authentication logs.',
        xpReward: 175,
      },
      {
        id: 'lesson-9-3',
        title: 'File Analysis and Regular Expressions',
        description: 'Find useful patterns in text files while handling untrusted content as data.',
        topics: ['Regex groups', 'Encoding errors', 'Secret-shaped strings', 'False positives'],
        learningObjectives: ['Write a focused regular expression', 'Handle decoding failures', 'Report findings without exposing sensitive values'],
        codeExample: 'SECRET_SHAPE = re.compile(r"\\b[A-Za-z0-9_-]{20,}\\b")\n\nfor match in SECRET_SHAPE.finditer(text):\n    print(match.start(), "<redacted>")',
        exercise: {
          prompt: 'Detect email-like strings in a text fixture and return only their locations, not the full values.',
          starterCode: 'def find_email_locations(text):\n    # return [(start, end), ...]\n    return []',
          expectedOutcome: 'Locations of likely matches with no secret value printed to the screen.',
        },
        challenge: 'Create a redacted scanner for a lab repository that reports candidate secrets by file and line number, while excluding its own output file.',
        hints: ['Use named patterns for readability.', 'Redact the middle of a match before displaying it.', 'Treat every match as a lead that requires review.'],
        quizPrompt: 'Ask why a pattern match is not enough to prove that a credential is active.',
        xpReward: 175,
      },
      {
        id: 'lesson-9-4',
        title: 'Safe Network Programming Concepts',
        description: 'Understand sockets and HTTP clients through controlled, allowlisted lab targets.',
        topics: ['Sockets and ports', 'Timeouts', 'Allowlisting', 'HTTP requests'],
        learningObjectives: ['Explain a client-server connection', 'Set timeouts and handle errors', 'Keep network code inside an authorized scope'],
        codeExample: 'from urllib.request import urlopen\n\nwith urlopen("http://lab.local/health", timeout=3) as response:\n    print(response.status)',
        exercise: {
          prompt: 'Design a health-check function that accepts only a lab hostname and returns status or a safe error.',
          starterCode: 'ALLOWED_HOSTS = {"lab.local"}\n\ndef check_health(url):\n    # validate host, apply timeout, return a small result\n    pass',
          expectedOutcome: 'A bounded request that refuses out-of-scope hosts and never hangs indefinitely.',
        },
        challenge: 'Build a read-only availability checker for three supplied lab endpoints and summarize timeout versus server-error results.',
        hints: ['Parse the URL before making the request.', 'Use a short timeout and catch expected network errors.', 'Never turn a health check into a scanner.'],
        quizPrompt: 'Ask which controls keep a network script inside an authorized lab boundary.',
        xpReward: 200,
      },
    ],
  },
  {
    id: 'module-10',
    title: 'Web Technologies for Security',
    icon: '🌐',
    level: 'Intermediate',
    track: 'web',
    description: 'Understand browser, JavaScript, and HTTP behavior so you can build and review safer web applications.',
    lessons: [
      {
        id: 'lesson-10-1',
        title: 'JavaScript in the Browser',
        description: 'Learn how browser scripts interact with the DOM, storage, and user-controlled data.',
        topics: ['DOM boundaries', 'Events', 'localStorage risks', 'Output encoding'],
        learningObjectives: ['Trace data from an input to a page sink', 'Identify unsafe HTML insertion', 'Choose textContent over innerHTML when appropriate'],
        codeExample: 'const output = document.querySelector("#output");\noutput.textContent = userSuppliedText;',
        exercise: {
          prompt: 'Replace an unsafe DOM update with a safe rendering approach and explain what changed.',
          starterCode: 'output.innerHTML = profile.displayName;',
          expectedOutcome: 'User-controlled text renders as text instead of being interpreted as markup.',
        },
        challenge: 'Review a simulated profile widget and list every user-controlled source, sink, and missing output-encoding control.',
        hints: ['Track values from URL parameters, forms, and storage.', 'A sanitizer is not a substitute for the correct context.', 'Test with harmless marker strings in the lab.'],
        quizPrompt: 'Ask the learner to explain why encoding must match the output context.',
        xpReward: 175,
      },
      {
        id: 'lesson-10-2',
        title: 'Browser Security Boundaries',
        description: 'Explore same-origin policy, cookies, CORS, and browser protections through safe examples.',
        topics: ['Origins', 'Same-origin policy', 'CORS', 'Cookie flags', 'Content Security Policy'],
        learningObjectives: ['Calculate whether two URLs share an origin', 'Explain what CORS does and does not protect', 'Select safer cookie attributes'],
        codeExample: 'Set-Cookie: session=...; Secure; HttpOnly; SameSite=Lax',
        exercise: {
          prompt: 'Given a request origin and server policy, decide whether the browser should allow the response to be read.',
          starterCode: 'allowed_origins = {"https://academy.test"}\nrequest_origin = "https://student.test"',
          expectedOutcome: 'A clear origin decision with a reason tied to the browser security model.',
        },
        challenge: 'Harden a simulated web app policy by choosing cookie flags, a narrow CORS allowlist, and a starter CSP.',
        hints: ['CORS controls browser reads, not whether a server receives a request.', 'Avoid wildcard origins when credentials are involved.', 'Start with the narrowest policy that supports the app.'],
        quizPrompt: 'Ask why HttpOnly helps against script access but does not stop every form of session abuse.',
        xpReward: 175,
      },
      {
        id: 'lesson-10-3',
        title: 'HTTP Requests and API Clients',
        description: 'Inspect request and response structure and build clients that handle untrusted data safely.',
        topics: ['Methods and status codes', 'Headers', 'JSON parsing', 'Validation', 'Timeouts'],
        learningObjectives: ['Read an HTTP exchange', 'Validate a JSON response before use', 'Handle non-success responses explicitly'],
        codeExample: 'response = client.get(url, timeout=3)\nresponse.raise_for_status()\ndata = response.json()',
        exercise: {
          prompt: 'Validate that an API response contains a string username and a list of roles before displaying it.',
          starterCode: 'def safe_profile(data):\n    # return a validated, minimal profile\n    pass',
          expectedOutcome: 'Only the expected fields and types are returned to the caller.',
        },
        challenge: 'Analyze a captured lab request and identify missing authentication, validation, and error-handling controls.',
        hints: ['Status code success does not guarantee a safe response shape.', 'Allowlist fields instead of copying arbitrary JSON.', 'Never log authorization headers.'],
        quizPrompt: 'Ask the learner why an API client should validate response data even when it uses HTTPS.',
        xpReward: 200,
      },
      {
        id: 'lesson-10-4',
        title: 'JavaScript Security Review',
        description: 'Perform a structured review of frontend code for injection, secrets, and unsafe assumptions.',
        topics: ['Client-side trust', 'Secrets in bundles', 'DOM XSS', 'Dependency risk'],
        learningObjectives: ['Separate UI checks from server authorization', 'Spot secrets that do not belong in frontend code', 'Prioritize findings by impact'],
        codeExample: 'if (!sessionUser.isAdmin) return;\n// UI checks improve experience; the server must enforce authorization.',
        exercise: {
          prompt: 'Mark which checks in a frontend snippet are cosmetic and which security decisions must move to the server.',
          starterCode: 'if (button.dataset.role === "admin") showDeleteButton();',
          expectedOutcome: 'A review that identifies the UI as untrusted and requests server-side authorization.',
        },
        challenge: 'Write a short security review for a simulated single-page app with three findings, evidence, severity, and remediation.',
        hints: ['Search for tokens, unsafe sinks, and trust in client-provided roles.', 'Describe impact without exaggerating exploitability.', 'Recommend the smallest durable fix.'],
        quizPrompt: 'Ask why hiding a button is not an authorization control.',
        xpReward: 200,
      },
    ],
  },
  {
    id: 'module-11',
    title: 'APIs, Databases & Secure Coding',
    icon: '🧩',
    level: 'Advanced',
    track: 'secure-coding',
    description: 'Design safer application boundaries with validation, authentication, authorization, and protected data handling.',
    lessons: [
      {
        id: 'lesson-11-1',
        title: 'API Design and Input Validation',
        description: 'Build predictable API boundaries that reject malformed or dangerous input early.',
        topics: ['Schemas', 'Allowlisting', 'Canonicalization', 'Error responses', 'Rate limits'],
        learningObjectives: ['Define a small input schema', 'Reject unexpected fields', 'Return useful errors without leaking internals'],
        codeExample: 'allowed = {"email", "display_name"}\nclean = {key: body[key] for key in allowed if key in body}',
        exercise: {
          prompt: 'Create a validator for a registration payload with a bounded username and a valid email shape.',
          starterCode: 'def validate_registration(body):\n    # return clean data or a list of errors\n    pass',
          expectedOutcome: 'A deterministic validator with length limits and no unexpected fields.',
        },
        challenge: 'Harden a simulated registration endpoint against oversized, extra, and incorrectly typed fields.',
        hints: ['Validate type before length.', 'Normalize only where the business rule permits it.', 'Return field-level errors, not stack traces.'],
        quizPrompt: 'Ask why validation must happen on the server even if the browser validates the form.',
        xpReward: 200,
      },
      {
        id: 'lesson-11-2',
        title: 'Authentication and Authorization',
        description: 'Understand identity, sessions, roles, and object-level authorization in real applications.',
        topics: ['Authentication', 'Sessions', 'RBAC', 'Object-level authorization', 'Account recovery'],
        learningObjectives: ['Separate authentication from authorization', 'Identify an IDOR risk', 'Choose safer session handling'],
        codeExample: 'record = await get_record(record_id)\nif record.owner_id != current_user.id:\n    return forbidden()',
        exercise: {
          prompt: 'Review an endpoint that accepts a record ID and decide what ownership check is missing.',
          starterCode: 'record = db.records.find_one({"_id": request.args["id"]})\nreturn jsonify(record)',
          expectedOutcome: 'A server-side authorization check tied to the authenticated user or allowed role.',
        },
        challenge: 'Fix a simulated profile API so users can view their own profile but cannot switch the ID to read another user.',
        hints: ['Never trust a user-supplied object ID by itself.', 'Authorize the action after loading the object.', 'Return the same safe response for missing and forbidden records when appropriate.'],
        quizPrompt: 'Ask the learner to identify the difference between “logged in” and “allowed to access this object.”',
        xpReward: 225,
      },
      {
        id: 'lesson-11-3',
        title: 'Database Security and Injection Prevention',
        description: 'Use parameterized queries, least privilege, and safe error handling around data stores.',
        topics: ['SQL injection', 'Parameterized queries', 'Database roles', 'Transactions', 'Error handling'],
        learningObjectives: ['Recognize query construction risk', 'Use parameter binding', 'Limit database permissions'],
        codeExample: 'cursor.execute("SELECT id FROM users WHERE email = %s", (email,))',
        exercise: {
          prompt: 'Convert a string-concatenated query into a parameterized query and explain why it is safer.',
          starterCode: 'query = "SELECT * FROM users WHERE email = \'" + email + "\'"',
          expectedOutcome: 'A query that keeps data separate from SQL instructions.',
        },
        challenge: 'Review a simulated account search service and propose fixes for injection, overbroad database access, and verbose errors.',
        hints: ['Escaping is not the primary defense for SQL queries.', 'Use a database account with only required permissions.', 'Do not expose query text to users.'],
        quizPrompt: 'Ask why parameterization protects the query structure but does not solve authorization.',
        xpReward: 225,
      },
      {
        id: 'lesson-11-4',
        title: 'Secure Coding and Cryptography in Practice',
        description: 'Apply secure defaults to secrets, passwords, tokens, and sensitive application data.',
        topics: ['Password hashing', 'Randomness', 'Secret management', 'Encryption choices', 'Threat modeling'],
        learningObjectives: ['Choose hashing for passwords and encryption for recoverable data', 'Use a cryptographic random source', 'Keep secrets out of source control'],
        codeExample: 'hashed = bcrypt.hashpw(password, bcrypt.gensalt())\nassert bcrypt.checkpw(candidate, hashed)',
        exercise: {
          prompt: 'Classify each data item as public, hashed, encrypted, or secret-managed: a password, a session token, and a user preference.',
          starterCode: 'classification = {\n    "password": None,\n    "session_token": None,\n    "user_preference": None,\n}',
          expectedOutcome: 'A reasoned choice based on whether the original value must be recovered.',
        },
        challenge: 'Threat-model a small login service and produce three concrete secure-coding changes with rationale.',
        hints: ['Ask what happens if the database is copied.', 'Use established libraries instead of inventing cryptography.', 'Rotate and scope secrets where possible.'],
        quizPrompt: 'Ask why passwords should be hashed rather than encrypted for storage.',
        xpReward: 250,
      },
    ],
  },
  {
    id: 'module-12',
    title: 'Defensive Labs & CTF Arena',
    icon: '🧪',
    level: 'Advanced',
    track: 'labs',
    description: 'Practice investigation, remediation, and CTF reasoning in controlled Cyber Academy environments.',
    lessons: [
      {
        id: 'lesson-12-1',
        title: 'Investigate Suspicious Login Logs',
        description: 'Use a controlled log set to reconstruct a password-spraying scenario and recommend containment.',
        topics: ['Timeline building', 'Authentication telemetry', 'Indicators vs evidence', 'Containment'],
        learningObjectives: ['Build a short incident timeline', 'Correlate usernames, IPs, and timestamps', 'Recommend a proportional next step'],
        labType: 'defensive-investigation',
        exercise: {
          prompt: 'Sort the supplied events into a timeline and mark which events deserve follow-up.',
          starterCode: 'events = load_lab_file("login-events.json")\n# sort and summarize events without changing the source',
          expectedOutcome: 'A timeline with evidence-backed observations and uncertainty called out.',
        },
        challenge: 'Identify the likely spray window, affected accounts, and two defensive controls from the simulated dataset.',
        hints: ['Look for many accounts targeted from one source.', 'Check both failures and the first successful login.', 'Preserve the original event order in your notes.'],
        quizPrompt: 'Ask which observation would increase confidence that the activity is coordinated.',
        xpReward: 250,
      },
      {
        id: 'lesson-12-2',
        title: 'Find and Fix an Insecure Input',
        description: 'Review an intentionally vulnerable lab form and apply the correct validation and output controls.',
        topics: ['Threat modeling', 'Input validation', 'Output encoding', 'Regression checks'],
        learningObjectives: ['Trace untrusted input through an app', 'Select a context-appropriate fix', 'Write a regression test'],
        labType: 'secure-code-review',
        exercise: {
          prompt: 'Locate the unsafe input-to-output path in the lab app and describe the smallest safe fix.',
          starterCode: 'function renderGreeting(name) {\n  return `<h1>Hello ${name}</h1>`;\n}',
          expectedOutcome: 'A fix that treats the name as text and a test that prevents regression.',
        },
        challenge: 'Patch the lab’s input flow, verify harmless marker strings render correctly, and explain why the fix works.',
        hints: ['Identify the output context first.', 'Prefer safe DOM APIs or framework escaping.', 'A client-only fix is incomplete if the server stores the value.'],
        quizPrompt: 'Ask why the same input may need different defenses in HTML, a URL, and a SQL query.',
        xpReward: 250,
      },
      {
        id: 'lesson-12-3',
        title: 'Analyze a Simulated HTTP Attack',
        description: 'Investigate captured requests from an owned lab service and separate signal from noise.',
        topics: ['HTTP telemetry', 'Request correlation', 'Web attack indicators', 'Detection logic'],
        learningObjectives: ['Group related requests', 'Identify suspicious patterns without overfitting', 'Write a useful detection hypothesis'],
        labType: 'traffic-analysis',
        exercise: {
          prompt: 'Inspect the supplied request capture and group requests by source, endpoint, and response status.',
          starterCode: 'requests = load_lab_file("http-capture.json")\n# produce a summary table for the analyst',
          expectedOutcome: 'A compact traffic summary with a clear reason for each flagged group.',
        },
        challenge: 'Write a detection rule for the simulated attack and list one benign behavior that could trigger it.',
        hints: ['Combine multiple weak signals.', 'Use response status and timing as context.', 'Document the false-positive path before proposing a block.'],
        quizPrompt: 'Ask why a single suspicious URL should not automatically trigger an incident declaration.',
        xpReward: 275,
      },
      {
        id: 'lesson-12-4',
        title: 'CTF Challenge: Evidence to Remediation',
        description: 'Complete an authorized, sandboxed challenge that rewards reasoning, documentation, and a defensive fix.',
        topics: ['CTF methodology', 'Evidence collection', 'Root cause', 'Remediation writing'],
        learningObjectives: ['Form and test a hypothesis', 'Record reproducible evidence', 'Connect a finding to a durable fix'],
        labType: 'ctf',
        exercise: {
          prompt: 'Use the challenge clues to rank hypotheses before testing them. Do not attack anything outside the supplied sandbox.',
          starterCode: 'hypotheses = [\n    "misconfigured access control",\n    "unsafe input handling",\n    "exposed debug data",\n]',
          expectedOutcome: 'A short hypothesis log showing what was tested and what evidence changed your mind.',
        },
        challenge: 'Solve the sandbox challenge, submit the flag or finding, explain the root cause, and propose a remediation that would survive retesting.',
        hints: ['Read the scope and evidence before probing.', 'Prefer the least invasive test that distinguishes hypotheses.', 'A flag without a root cause is not a complete security finding.'],
        quizPrompt: 'Ask the learner what makes a CTF solution useful to a defender after the challenge ends.',
        xpReward: 300,
      },
    ],
  },
];

export function getLessonById(lessonId) {
  for (const module of curriculum) {
    const lesson = module.lessons.find(l => l.id === lessonId);
    if (lesson) return { ...lesson, moduleTitle: module.title, moduleLevel: module.level };
  }
  return null;
}
